# Dependencies
markdown:         redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments:         true

# Permalinks
permalink:        pretty

# Server
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

# the excluded directoies
exclude:
  - "conf"
  - "tools"

# site information
info:
  site_name:    Jekyll Multiple Languages Plugin

meta:
  description:  The best multiple languages plugin for Jekyll
  keywords:     Jekyll multiple languages plugin
  author:       liaohuqiu@gmail.com

# Multiple languages
languages:          ['en', 'cn']

# If not config, the first of languages will be the default
language_default:   'en'

# If a post of default language not set `no_fill_default_content` to true
# Its content will use to replace if the corresponding content of other languages is not exist.
# 
fill_default_content: true

navigation:
  en:
    title:    Jekyll Multiple Languages
    items1:
      - path:     
        title:    
      - path:    
        title:  
  cn:
    title:    Jekyll Multiple Languages
    items1:
      - path:    
        title:  
      - path:  
        title:

right_nav:
  - title:    English Version
    url:      /
  - title:    中文版文档
    url:      /cn
  - title:    Fork on Github
    url:     https://github.com/liaohuqiu/jekyll-multiple-languages

# analytics account info
analytics:
  google:
    account:    UA-43024238-4

# other informations about this project
download:
  rep:          https://github.com/liaohuqiu/jekyll-multiple-languages
  dist:         https://github.com/liaohuqiu/jekyll-multiple-languages/archive/master.zip
